---

apache_vhosts:
  - server_name: default.local
    server_admin: webmaster@palaso.org
    server_file_name: default_local
    template: vhost_ssl.conf.j2
    document_root: /var/www/virtual/default_local
    directory_options:
      - "+Indexes"
      - "+FollowSymLinks"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: []
  - server_name: languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org
    template: vhost_ssl.conf.j2
    document_root: /var/www/virtual/languageforge.org/htdocs
    link_to: "/var/www/virtual/default_local/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - languageforge.local
  - server_name: scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org
    template: vhost_ssl.conf.j2
    document_root: /var/www/virtual/scriptureforge.org/htdocs
    link_to: "/var/www/virtual/default_local/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - scriptureforge.local
      - has_ssl: true
        port: 443
        certificate_file: "scriptureforge.pem"
        key_file: "scriptureforge.key"
