# https://docs.docker.com/compose/compose-file
version: '3.5'
services:
  ui:
    build:
      context: ..
      dockerfile: docker/ui/Dockerfile
    image: lf-ui
    container_name: lf-ui
    depends_on:
      - api
    volumes:
      # share dist folder between ui and api containers
      - lf-webpack-dist-folder:/data/src/dist

      # for developer convenience
      - ../src:/data/src
      - ../typings:/data/typings
      - ../webpack.config.js:/data/webpack.config.js
      - ../gulpfile.js:/data/gulpfile.js

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    image: lf-api
    container_name: lf-api
    depends_on:
      - db
      - mail
    environment:
      - WAIT_HOSTS=db:27017, mail:25
    command: sh -c "/wait && apache2-foreground"
    volumes:
      # share dist folder between ui and api containers
      - lf-webpack-dist-folder:/var/www/src/dist

      # persist user data uploads and assets
      - lf-user-data-assets:/var/www/src/assets

      # for developer convenience
      - ../src/Api:/var/www/src/Api
      - ../src/Site:/var/www/src/Site

  ssl:
    image: caddy
    container_name: lf-ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ui
    volumes:
      - lf-caddy-data:/data
      - lf-caddy-config:/config
    # https://caddyserver.com/docs/command-line
    command: caddy reverse-proxy --from localhost --to api
    restart: unless-stopped

  mail:
    build:
      context: .
      dockerfile: mail/Dockerfile
    image: lf-mail
    container_name: lf-mail

  db:
    image: mongo:4.0
    container_name: lf-db
    ports:
      # exposed this to host for admin tools
      - 27017:27017
    volumes:
      - lf-mongo-data:/data/db
    restart: always

  # TODO: still needs to be built/run/tested, etc.
  # lfmerge:
  #   container_name: lfmerge
  #   build: lfmerge/.
  #   volumes:
  #     - lfmerge-data:/var/lib/languageforge

  selenium:
    # image: selenium/standalone-chrome
    image: selenium/standalone-chrome-debug
    # TODO: seems would should have a depends_on for the e2e-api
    links:
      # TODO:  I wonder why this was necessary, I would've thought e2e-api was already available, maybe not?
      - "e2e-api:e2e"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"

  e2e-ui:
    build:
      context: ..
      dockerfile: docker/e2e-ui/Dockerfile
    image: e2e-ui
    container_name: e2e-ui
    depends_on:
      - db
      - e2e-api
      - mail
      - selenium
    environment:
      - WAIT_HOSTS=db:27017, mail:25, selenium:4444
    command: sh -c "/wait && /run.sh"
    volumes:
      # share dist folder between ui and api containers
      - lf-webpack-dist-folder:/data/src/dist

      # for developer convenience
      - ../src:/data/src
      - ../typings:/data/typings
      - ../webpack.config.js:/data/webpack.config.js
      - ../gulpfile.js:/data/gulpfile.js

  e2e-api:
    build:
      context: ..
      dockerfile: docker/e2e-api/Dockerfile
    image: e2e-api
    container_name: e2e-api
    depends_on:
      - db
      - mail
    environment:
      - WAIT_HOSTS=db:27017, mail:25
    command: sh -c "/wait && /run.sh"
    volumes:
      # share dist folder between ui and api containers
      - lf-webpack-dist-folder:/var/www/src/dist

  test-api:
    # TODO: get XDebug working with VSCode
    build:
      context: ..
      dockerfile: docker/test-api/Dockerfile
    image: test-api
    container_name: test-api
    depends_on:
      - db
      - mail
    environment:
      - WAIT_HOSTS=db:27017, mail:25
    command: sh -c "/wait && /run.sh"
    volumes:
      # for developer convenience
      - ../test:/var/www/test

  db-reset:
    build:
      context: ..
      dockerfile: docker/db-reset/Dockerfile
    volumes:
      # for developer convenience
      - ../scripts/:/var/www/scripts
    depends_on:
      - mail
      - db

volumes:
  lf-caddy-config:
  lf-caddy-data:
  lf-mongo-data:
  lf-user-data-assets:
  lf-webpack-dist-folder:
