---

apache_install: false

# apache_module_disable: false
# apache_module_enable:
#   - rewrite
#   - ssl

apache_site_disable: []
#   - 000-default
#   - default-ssl
apache_site_enable:
  - languageforge_org_dev.conf
  - scriptureforge_org_dev.conf
  - languageforge_org_e2etest.conf
  - scriptureforge_org_e2etest.conf

apache_vhosts:
  - server_name: dev.languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org_dev
    document_root: /var/www/languageforge.org_dev/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: []
      - has_ssl: true
        port: 443
        server_alias: []
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/dev.languageforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "languageforge_org_dev.pem"
        chain_file: "languageforge_org_dev.pem"
        key_file: "languageforge_org_dev.key"
  - server_name: dev.scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org_dev
    document_root: /var/www/scriptureforge.org_dev/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - jamaicanpsalms.dev.scriptureforge.org
      - has_ssl: true
        port: 443
        server_alias: []
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/dev.scriptureforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "scriptureforge_org_dev.pem"
        chain_file: "scriptureforge_org_dev.pem"
        key_file: "scriptureforge_org_dev.key"
  - server_name: e2etest.languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org_e2etest
    document_root: /var/www/languageforge.org_e2etest/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: []
      - has_ssl: true
        port: 443
        server_alias: []
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/e2etest.languageforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "languageforge_org_e2etest.pem"
        chain_file: "languageforge_org_e2etest.pem"
        key_file: "languageforge_org_e2etest.key"
  - server_name: e2etest.scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org_e2etest
    document_root: /var/www/scriptureforge.org_e2etest/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: [] 
      - has_ssl: true
        port: 443
        server_alias:
          - jamaicanpsalms.e2etest.scriptureforge.org
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/e2etest.scriptureforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "scriptureforge_org_e2etest.pem"
        chain_file: "scriptureforge_org_e2etest.pem"
        key_file: "scriptureforge_org_e2etest.key"
