---

# config_developer

# mongo_path: /hddlinux/mongodb
mongo_path: /var/lib/mongodb
php_log_folder: /var/log/php
lf_path: /var/www/default_local/web-languageforge
site_src_paths:
  - "{{lf_path}}/src"

### Version/distro
base_distribution: "{{ansible_distribution | lower}}"
base_distribution_release: "focal"
# The mongodb-org packages are not yet available for Focal Fossa as of 2020-07-21, so leave this as "bionic" until they are
base_distribution_release_for_mongo: "bionic"
# The linux.lsdev.sil.org repo does not yet have Focal packages as of 2020-07-21, so leave this as "bionic" until Focal is available
base_distribution_release_for_llso: "bionic"

# Once we update this to 4.4, also uncomment the appropriate mongodb_signing_key line below
mongodb_version: 4.2
# PHP 7.4 makes some backwards-incompatible changes that break Language Forge, so we'll get 7.3 from the PPA
php_version: 7.3

# 4.0
#mongodb_signing_key: 9DA31620334BD75D9DCB49F368818C72E52529D4
# 4.2
mongodb_signing_key: E162F504A20CDF15827F718D4B7C549A058F8B6B
# 4.4
#mongodb_signing_key: 20691EEC35216C63CAF66CE1656408E390CFB1F5

### SSL config
ssl_letsencrypt_install: false

ssl_items:
  - name: languageforge
    state: selfsign
    request:
        country_code: "TH"
        state: "Chiang Mai"
        locality: "Chiang Mai"
        organization: "SIL"
        organization_unit: ""
        common_name: "languageforge.localhost"
        alt_names:
          - key: DNS.1
            value: "www.languageforge.localhost"
          - key: DNS.2
            value: "languageforge.localhost"
    sign:


### Apache config
apache_module_enable:
  - headers
  - proxy
  - proxy_http
  - proxy_wstunnel
  - rewrite
  - ssl

apache_site_enable:
  - default_local.conf
  - languageforge_org.conf

apache_vhosts:
  - server_name: default.local
    server_admin: webmaster@palaso.org
    server_file_name: default_local
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/default_local
    directory_options:
      - "+Indexes"
      - "+FollowSymLinks"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - localhost
  - server_name: languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/languageforge.org/htdocs
    link_to: "{{lf_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - languageforge.localhost
          - localhost
        extra:
          - '<ifModule mod_headers.c>'
          - '    <Files "service-worker.js">'
          - '        Header Set Service-Worker-allowed "/"'
          - '    </Files>'
          - '</IfModule>'
