---

# config_developer

# mongo_path: /hddlinux/mongodb
mongo_path: /var/lib/mongodb
php_log_folder: /var/log/php
lf_path: /var/www/default_local/web-languageforge
sf_path: /var/www/default_local/web-languageforge
site_src_paths:
  - "{{lf_path}}/src"
  - "{{sf_path}}/src"

### Version/distro
base_distribution: "{{ansible_distribution | lower}}"
# The mongodb-org packages are not yet available for Focal Fossa as of 2020-07-21, so leave this as "bionic" until they are
base_distribution_release: "bionic"

node_version: 10.17.0
npm_version: 6.14.4
# Once we update this to 4.4, also uncomment the appropriate mongodb_signing_key line below
mongodb_version: 4.2
php_version: 7.4

# 4.0
#mongodb_signing_key: 9DA31620334BD75D9DCB49F368818C72E52529D4
# 4.2
mongodb_signing_key: E162F504A20CDF15827F718D4B7C549A058F8B6B
# 4.4
#mongodb_signing_key: 20691EEC35216C63CAF66CE1656408E390CFB1F5

### SSL config
ssl_letsencrypt_install: false

ssl_items:
  - name: scriptureforge
    state: selfsign
    request:
        country_code: "TH"
        state: "Chiang Mai"
        locality: "Chiang Mai"
        organization: "SIL"
        organization_unit: ""
        common_name: "scriptureforge.localhost"
        alt_names:
          - key: DNS.1
            value: "www.scriptureforge.localhost"
          - key: DNS.2
            value: "scriptureforge.localhost"
    sign:


### Apache config
apache_module_enable:
  - headers
  - proxy
  - proxy_http
  - proxy_wstunnel
  - rewrite
  - ssl

apache_site_enable:
  - default_local.conf
  - languageforge_org.conf
  - scriptureforge_org.conf

apache_vhosts:
  - server_name: default.local
    server_admin: webmaster@palaso.org
    server_file_name: default_local
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/default_local
    directory_options:
      - "+Indexes"
      - "+FollowSymLinks"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - localhost
  - server_name: languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/languageforge.org/htdocs
    link_to: "{{lf_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - languageforge.localhost
          - localhost
        extra:
          - '<ifModule mod_headers.c>'
          - '    <Files "service-worker.js">'
          - '        Header Set Service-Worker-allowed "/"'
          - '    </Files>'
          - '</IfModule>'
  - server_name: scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/scriptureforge.org/htdocs
    link_to: "{{sf_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - scriptureforge.localhost
          - localhost
        extra:
        - '<ifModule mod_headers.c>'
        - '    <Files "service-worker.js">'
        - '        Header Set Service-Worker-allowed "/"'
        - '    </Files>'
        - '</IfModule>'
      - has_ssl: true
        port: 443
        certificate_file: "scriptureforge.pem"
        key_file: "scriptureforge.key"
        extra:
        - '<ifModule mod_headers.c>'
        - '    <Files "service-worker.js">'
        - '        Header Set Service-Worker-allowed "/"'
        - '    </Files>'
        - '</IfModule>'
