# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app

---

# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: languageforge-app
spec:
  rules:
  - host: qa.languageforge.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: app
            port:
              number: 80
  tls:
  - hosts:
    - qa.languageforge.com

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: sillsdev/web-languageforge:app-latest
        imagePullPolicy: Always # TODO: this can be removed (or changed to IfNotPresent) once the image is being tagged properly.
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        env:
          - name: DATABASE
            value: scriptureforge
          - name: ENVIRONMENT
            value: {{ENVIRONMENT}}
          - name: WEBSITE
            value: {{WEBSITE}}
          - name: MONGODB_CONN
            valueFrom:
              secretKeyRef:
                key: MONGODB_CONN
                name: app
          - name: REMEMBER_ME_SECRET
            valueFrom:
              secretKeyRef:
                key: REMEMBER_ME_SECRET
                name: app
          - name: LDAPI_BASE_URL
            valueFrom:
              secretKeyRef:
                key: LDAPI_BASE_URL
                name: ld-api
          - name: LANGUAGE_DEPOT_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: LANGUAGE_DEPOT_API_TOKEN
                name: ld-api
          - name: FACEBOOK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: FACEBOOK_CLIENT_ID
                name: oauth
          - name: FACEBOOK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: FACEBOOK_CLIENT_SECRET
                name: oauth
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_ID
                name: oauth
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_SECRET
                name: oauth
