# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mail-from-kubectl
  name: mail-from-kubectl
spec:
  selector:
    matchLabels:
      app: mail-from-kubectl
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: mail-from-kubectl
    spec:
      containers:
      - name: mail-from-kubectl
        image: juanluisbaptiste/postfix:1.0.0
        env:
          - name: SERVER_HOSTNAME
            value: {{SERVER_HOSTNAME}}
          - name: SMTP_SERVER
            valueFrom:
              secretKeyRef:
                key: SMTP_SERVER
                name: mail
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                key: SMTP_USERNAME
                name: mail
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SMTP_PASSWORD
                name: mail

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail-from-kubectl
  name: mail-from-kubectl
spec:
  type: ClusterIP
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    app: mail-from-kubectl
