# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail
  name: mail
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mail
---

  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mail
  name: mail
spec:
  selector:
    matchLabels:
      app: mail
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mail
        image: juanluisbaptiste/postfix:1.0.0
        env:
          - name: SERVER_HOSTNAME
            value: {{SERVER_HOSTNAME}}
          - name: SMTP_SERVER
            valueFrom:
              secretKeyRef:
                key: SMTP_SERVER
                name: mail
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                key: SMTP_USERNAME
                name: mail
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SMTP_PASSWORD
                name: mail
