name: Deploy to Docker Hub

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - 'chore/docker-deployment'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-images:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Reveal environment
        run: |
          docker --version
          docker-compose --version
          make --version
          cat /proc/cpuinfo
          free
          df -h

      - name: Build app
        run: |
          cd docker
          make deployable-app

      - name: Reveal images
        run: docker images
